spring.application.name=config-server-1
# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=client_id
spring.security.oauth2.client.registration.google.client-secret=secret_key

# Scopes (important to get email + name)
spring.security.oauth2.client.registration.google.scope=openid,profile,email

